// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package us.hennepin.domain;

import org.springframework.beans.factory.annotation.Configurable;
import us.hennepin.domain.JunkEntityIntegrationTest;

privileged aspect JunkEntityIntegrationTest_Roo_Configurable {
    
    declare @type: JunkEntityIntegrationTest: @Configurable;
    
}
