// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package us.hennepin.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import us.hennepin.domain.JunkEntity;
import us.hennepin.domain.JunkEntityDataOnDemand;
import us.hennepin.domain.JunkEntityIntegrationTest;

privileged aspect JunkEntityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JunkEntityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JunkEntityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JunkEntityIntegrationTest: @Transactional;
    
    @Autowired
    private JunkEntityDataOnDemand JunkEntityIntegrationTest.dod;
    
    @Test
    public void JunkEntityIntegrationTest.testCountJunkEntitys() {
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to initialize correctly", dod.getRandomJunkEntity());
        long count = JunkEntity.countJunkEntitys();
        Assert.assertTrue("Counter for 'JunkEntity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JunkEntityIntegrationTest.testFindJunkEntity() {
        JunkEntity obj = dod.getRandomJunkEntity();
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to provide an identifier", id);
        obj = JunkEntity.findJunkEntity(id);
        Assert.assertNotNull("Find method for 'JunkEntity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JunkEntity' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JunkEntityIntegrationTest.testFindAllJunkEntitys() {
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to initialize correctly", dod.getRandomJunkEntity());
        long count = JunkEntity.countJunkEntitys();
        Assert.assertTrue("Too expensive to perform a find all test for 'JunkEntity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JunkEntity> result = JunkEntity.findAllJunkEntitys();
        Assert.assertNotNull("Find all method for 'JunkEntity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JunkEntity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JunkEntityIntegrationTest.testFindJunkEntityEntries() {
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to initialize correctly", dod.getRandomJunkEntity());
        long count = JunkEntity.countJunkEntitys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JunkEntity> result = JunkEntity.findJunkEntityEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JunkEntity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JunkEntity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JunkEntityIntegrationTest.testFlush() {
        JunkEntity obj = dod.getRandomJunkEntity();
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to provide an identifier", id);
        obj = JunkEntity.findJunkEntity(id);
        Assert.assertNotNull("Find method for 'JunkEntity' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJunkEntity(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JunkEntity' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JunkEntityIntegrationTest.testMergeUpdate() {
        JunkEntity obj = dod.getRandomJunkEntity();
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to provide an identifier", id);
        obj = JunkEntity.findJunkEntity(id);
        boolean modified =  dod.modifyJunkEntity(obj);
        Integer currentVersion = obj.getVersion();
        JunkEntity merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JunkEntity' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JunkEntityIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to initialize correctly", dod.getRandomJunkEntity());
        JunkEntity obj = dod.getNewTransientJunkEntity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JunkEntity' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'JunkEntity' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JunkEntityIntegrationTest.testRemove() {
        JunkEntity obj = dod.getRandomJunkEntity();
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JunkEntity' failed to provide an identifier", id);
        obj = JunkEntity.findJunkEntity(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JunkEntity' with identifier '" + id + "'", JunkEntity.findJunkEntity(id));
    }
    
}
