// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package us.hennepin.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import us.hennepin.domain.JunkEntity;
import us.hennepin.domain.JunkEntityDataOnDemand;

privileged aspect JunkEntityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JunkEntityDataOnDemand: @Component;
    
    private Random JunkEntityDataOnDemand.rnd = new SecureRandom();
    
    private List<JunkEntity> JunkEntityDataOnDemand.data;
    
    public JunkEntity JunkEntityDataOnDemand.getNewTransientJunkEntity(int index) {
        JunkEntity obj = new JunkEntity();
        setDateForSomeReason(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void JunkEntityDataOnDemand.setDateForSomeReason(JunkEntity obj, int index) {
        Date dateForSomeReason = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDateForSomeReason(dateForSomeReason);
    }
    
    public void JunkEntityDataOnDemand.setName(JunkEntity obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public JunkEntity JunkEntityDataOnDemand.getSpecificJunkEntity(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JunkEntity obj = data.get(index);
        Long id = obj.getId();
        return JunkEntity.findJunkEntity(id);
    }
    
    public JunkEntity JunkEntityDataOnDemand.getRandomJunkEntity() {
        init();
        JunkEntity obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JunkEntity.findJunkEntity(id);
    }
    
    public boolean JunkEntityDataOnDemand.modifyJunkEntity(JunkEntity obj) {
        return false;
    }
    
    public void JunkEntityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JunkEntity.findJunkEntityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JunkEntity' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JunkEntity>();
        for (int i = 0; i < 10; i++) {
            JunkEntity obj = getNewTransientJunkEntity(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
